# Generated by Django 5.1.6 on 2025-02-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
