# Generated by Django 5.1.6 on 2025-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Username'),
        ),
    ]
