# Generated by Django 5.1.6 on 2025-02-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0004_owner_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='Club_name')),
                ('club_owner_name', models.CharField(max_length=100, null=True, verbose_name='Club_owner_name')),
                ('club_id', models.CharField(max_length=100, null=True, verbose_name='Club_id')),
                ('club_email', models.EmailField(max_length=100, verbose_name='Club_email')),
                ('club_owner_email', models.EmailField(max_length=100, null=True, verbose_name='Club_owner_email')),
                ('club_category', models.CharField(max_length=100, null=True, verbose_name='Club_category')),
                ('club_phone', models.CharField(max_length=50, null=True, verbose_name='Club_phone')),
                ('club_owner_mobile', models.CharField(max_length=50, null=True, verbose_name='Club_owner_mobile')),
                ('club_password', models.CharField(max_length=100, verbose_name='Club_password')),
                ('club_address', models.CharField(max_length=100, null=True, verbose_name='Club_address')),
                ('club_city', models.CharField(max_length=30, null=True, verbose_name='Club_city')),
                ('club_state', models.CharField(max_length=30, null=True, verbose_name='Club_state')),
                ('club_country', models.CharField(max_length=30, null=True, verbose_name='Club_country')),
                ('club_description', models.CharField(max_length=1000, null=True, verbose_name='Club_description')),
                ('club_detail_description', models.CharField(max_length=2000, null=True, verbose_name='Club_detail_description')),
                ('club_image', models.ImageField(blank=True, null=True, upload_to='club_image')),
            ],
        ),
    ]
