# Generated by Django 5.1.6 on 2025-02-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0005_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_id',
        ),
    ]
