# Generated by Django 5.1.6 on 2025-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0006_remove_club_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_image',
        ),
    ]
