# Generated by Django 5.1.6 on 2025-02-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0007_remove_club_club_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='Club_Detail',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Owner_Detail',
        ),
        migrations.RenameModel(
            old_name='Owner',
            new_name='User_Detail',
        ),
    ]
