# Generated by Django 5.1.6 on 2025-02-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0008_rename_club_club_detail_rename_user_owner_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club_Detail',
        ),
        migrations.DeleteModel(
            name='Owner_Detail',
        ),
        migrations.DeleteModel(
            name='User_Detail',
        ),
    ]
