# Generated by Django 5.1.6 on 2025-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp_app', '0009_delete_club_detail_delete_owner_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='Club_name')),
                ('club_owner_name', models.CharField(max_length=100, null=True, verbose_name='Club_owner_name')),
                ('club_email', models.EmailField(max_length=100, verbose_name='Club_email')),
                ('club_owner_email', models.EmailField(max_length=100, null=True, verbose_name='Club_owner_email')),
                ('club_category', models.CharField(max_length=100, null=True, verbose_name='Club_category')),
                ('club_phone', models.CharField(max_length=50, null=True, verbose_name='Club_phone')),
                ('club_owner_mobile', models.CharField(max_length=50, null=True, verbose_name='Club_owner_mobile')),
                ('club_password', models.CharField(max_length=100, verbose_name='Club_password')),
                ('club_address', models.CharField(max_length=100, null=True, verbose_name='Club_address')),
                ('club_city', models.CharField(max_length=30, null=True, verbose_name='Club_city')),
                ('club_state', models.CharField(max_length=30, null=True, verbose_name='Club_state')),
                ('club_country', models.CharField(max_length=30, null=True, verbose_name='Club_country')),
                ('club_description', models.CharField(max_length=1000, null=True, verbose_name='Club_description')),
                ('club_detail_description', models.CharField(max_length=2000, null=True, verbose_name='Club_detail_description')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Detail',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
            ],
        ),
    ]
