# Generated by Django 5.1.6 on 2025-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
