# Generated by Django 5.1.6 on 2025-02-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0011_owner_detail_profile_image_user_detail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/owner'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/user'),
        ),
    ]
