# Generated by Django 5.1.6 on 2025-02-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0012_alter_owner_detail_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_image', models.ImageField(null=True, upload_to='exp_app/static/images/club')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_detail')),
            ],
        ),
    ]
