# Generated by Django 5.1.6 on 2025-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0013_club_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_image',
            name='club',
        ),
        migrations.DeleteModel(
            name='Owner_Detail',
        ),
        migrations.DeleteModel(
            name='User_Detail',
        ),
        migrations.DeleteModel(
            name='Club_Detail',
        ),
        migrations.DeleteModel(
            name='Club_Image',
        ),
    ]
