# Generated by Django 5.1.6 on 2025-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_detail',
            name='club_profile_image',
            field=models.ImageField(null=True, upload_to='exp_app/static/images/club'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='exp_app/static/images/user'),
        ),
    ]
