# Generated by Django 5.1.6 on 2025-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0016_club_detail_club_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/user'),
        ),
    ]
