# Generated by Django 5.1.6 on 2025-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0017_alter_user_detail_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email_id')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
