# Generated by Django 5.1.6 on 2025-02-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0022_delete_club_inquiry_detail_delete_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/user')),
            ],
        ),
        migrations.CreateModel(
            name='Club_Inquiry_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True, verbose_name='Event Name')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('time_slot', models.CharField(max_length=100, null=True, verbose_name='Time Slot')),
                ('budget', models.CharField(max_length=100, null=True, verbose_name='Budget')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_detail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.user_detail')),
            ],
        ),
    ]
