# Generated by Django 5.1.6 on 2025-03-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0025_club_inquiry_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club_Inquiry_Detail',
        ),
    ]
