# Generated by Django 5.1.6 on 2025-03-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0028_delete_club_inquiry_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Inquiry_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('time_slot', models.CharField(max_length=100, null=True, verbose_name='Time Slot')),
                ('budget', models.CharField(max_length=100, null=True, verbose_name='Budget')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('status_reason', models.CharField(max_length=100, verbose_name='Status Reason')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_detail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.user_detail')),
            ],
        ),
    ]
