# Generated by Django 5.1.6 on 2025-03-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0029_club_inquiry_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_inquiry_detail',
            name='status_reason',
            field=models.CharField(max_length=100, null=True, verbose_name='Status Reason'),
        ),
    ]
