# Generated by Django 5.1.6 on 2025-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0030_alter_club_inquiry_detail_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_detail',
            name='club_profile_image',
            field=models.ImageField(null=True, upload_to='media/club'),
        ),
        migrations.AlterField(
            model_name='club_image',
            name='club_image',
            field=models.ImageField(null=True, upload_to='media/club'),
        ),
        migrations.AlterField(
            model_name='owner_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/owner'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user'),
        ),
    ]
