# Generated by Django 5.1.6 on 2025-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0031_alter_club_detail_club_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='club_detail',
            name='club_profile_image',
            field=models.ImageField(null=True, upload_to='exp_app/static/images/club'),
        ),
        migrations.AlterField(
            model_name='club_image',
            name='club_image',
            field=models.ImageField(null=True, upload_to='exp_app/static/images/club'),
        ),
        migrations.AlterField(
            model_name='owner_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/owner'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/user'),
        ),
    ]
