# Generated by Django 5.1.6 on 2025-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0032_delete_contact_alter_club_detail_club_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email_id')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
