# Generated by Django 5.1.6 on 2025-03-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0034_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_inquiry_detail')),
            ],
        ),
    ]
