# Generated by Django 5.1.6 on 2025-04-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp_app', '0036_remove_club_inquiry_detail_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='Club_name')),
                ('club_profile_image', models.ImageField(null=True, upload_to='exp_app/static/images/club')),
                ('club_owner_name', models.CharField(max_length=100, null=True, verbose_name='Club_owner_name')),
                ('club_email', models.EmailField(max_length=100, verbose_name='Club_email')),
                ('club_owner_email', models.EmailField(max_length=100, null=True, verbose_name='Club_owner_email')),
                ('club_category', models.CharField(max_length=100, null=True, verbose_name='Club_category')),
                ('club_phone', models.CharField(max_length=50, null=True, verbose_name='Club_phone')),
                ('club_owner_mobile', models.CharField(max_length=50, null=True, verbose_name='Club_owner_mobile')),
                ('club_password', models.CharField(max_length=100, verbose_name='Club_password')),
                ('club_address', models.CharField(max_length=100, null=True, verbose_name='Club_address')),
                ('club_city', models.CharField(max_length=30, null=True, verbose_name='Club_city')),
                ('club_state', models.CharField(max_length=30, null=True, verbose_name='Club_state')),
                ('club_country', models.CharField(max_length=30, null=True, verbose_name='Club_country')),
                ('club_description', models.CharField(max_length=1000, null=True, verbose_name='Club_description')),
                ('club_detail_description', models.CharField(max_length=2000, null=True, verbose_name='Club_detail_description')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email_id')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Detail',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/owner')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email_id')),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Username')),
                ('mobile_number', models.CharField(max_length=10, null=True, verbose_name='Mobile_number')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('email', models.EmailField(max_length=100, verbose_name='Email_id')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='exp_app/static/images/user')),
            ],
        ),
        migrations.CreateModel(
            name='Club_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_image', models.ImageField(null=True, upload_to='exp_app/static/images/club')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Club_Inquiry_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('time_slot', models.CharField(max_length=100, null=True, verbose_name='Time Slot')),
                ('budget', models.CharField(max_length=100, null=True, verbose_name='Budget')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('status_reason', models.CharField(max_length=100, null=True, verbose_name='Status Reason')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_detail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Paid_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exp_app.club_inquiry_detail')),
            ],
        ),
    ]
