# Generated by Django 5.1.6 on 2025-04-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0037_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_inquiry_detail',
            name='club',
        ),
        migrations.RemoveField(
            model_name='club_image',
            name='club',
        ),
        migrations.RemoveField(
            model_name='club_inquiry_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paid_customer',
            name='payer',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Owner_Detail',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Club_Detail',
        ),
        migrations.DeleteModel(
            name='Club_Image',
        ),
        migrations.DeleteModel(
            name='User_Detail',
        ),
        migrations.DeleteModel(
            name='Club_Inquiry_Detail',
        ),
        migrations.DeleteModel(
            name='Paid_Customer',
        ),
    ]
